create table "public"."profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" text not null,
    "email" text,
    "first_name" text,
    "last_name" text,
    "about" text,
    "username" text,
    "avatar_url" text
      );


alter table "public"."profiles" enable row level security;

alter table "public"."portfolios" add column "file_type" text not null;

alter table "public"."portfolios" add column "file_url" text not null;

alter table "public"."portfolios" add column "user_id" text not null;

alter table "public"."users" alter column "id" set generated by default;

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_user_id_key ON public.profiles USING btree (user_id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."portfolios" add constraint "portfolios_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) not valid;

alter table "public"."portfolios" validate constraint "portfolios_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_user_id_key" UNIQUE using index "profiles_user_id_key";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Allow insert"
  on "public"."portfolio_images"
  as permissive
  for insert
  to public
with check ((auth.uid() IS NOT NULL));



  create policy "Allow select"
  on "public"."portfolio_images"
  as permissive
  for select
  to public
using (true);